export const ActionTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  SET_MOVIES_DATA: "SET_MOVIES_DATA",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
